/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.wm.java-conventions")
}

dependencies {
    api(project(":boogle-system"))
    implementation("org.springframework.boot:spring-boot-starter-thymeleaf")
    implementation("org.webjars:bootstrap:5.1.3")
    implementation("org.webjars.npm:whatwg-fetch:3.6.2")
    implementation("org.webjars.npm:bootstrap-icons:1.8.2")
    implementation("org.webjars:font-awesome:6.1.0")
    implementation("org.webjars:jquery:3.6.0")
    implementation("org.webjars:jquery-blockui:2.70-1")
    implementation("org.springframework.boot:spring-boot-starter-jdbc")
    api("org.springframework.security:spring-security-oauth2-authorization-server:1.0.0")
}

description = "统一认证授权服务模块"
